// ACE Sanitäter
force force ace_medical_treatment_medicAdenosine = 1; //Medics
force force ace_medical_treatment_medicEpinephrine = 1; //Medics
force force ace_medical_treatment_medicIV = 1; //Medics
force force ace_medical_treatment_medicMorphine = 1; //Medics
force force ace_medical_treatment_medicPAK = 2; //Doctors
force force ace_medical_treatment_medicSplint = 1; //Doctors
force force ace_medical_treatment_medicSurgicalKit = 1; //Medics

force force ace_medical_treatment_locationAdenosine = 0; //überall
force force ace_medical_treatment_locationEpinephrine = 0; //überall
force ace_medical_treatment_locationIV = 0; //überall
force force ace_medical_treatment_locationMorphine = 0; //überall
force ace_medical_treatment_locationPAK = 3; //Fhz oder Einrichtung
force ace_medical_treatment_locationsBoostTraining = false;
force ace_medical_treatment_locationSurgicalKit = 0; //überall

//ACE Cookoff
force ace_cookoff_enableAmmobox = false;

//KAM Vitals
force force kat_vitals_basicDiagnosticTime = 10;
force force kat_vitals_enableBasicDiagnostic = true;
force force kat_vitals_enableFluidShift = true;
force force kat_vitals_enableSimpleMedical = false;

//KAM Uhren
force force kat_watch_altitudeUnit = 0;
force force kat_watch_pressureUnit = 0;
force force kat_watch_temperatureUnit = 0;
force force kat_watch_watchInaccuracy = false;

//KAM Surgery
force force kat_surgery_closedLocation = 0;
force force kat_surgery_closedReduction_MedLevel = 2;
force force kat_surgery_closedReductionFailChance = 10;
force force kat_surgery_closedTime = 10;
force force kat_surgery_compoundChance = 30;
force force kat_surgery_enable_fracture = false;
force force kat_surgery_enable_selfCheckFracture = 1;
force force kat_surgery_fractureCheck_MedLevel = 0;
force force kat_surgery_fractureCheck_Time = 10;
force force kat_surgery_incisionTime = 10;
force force kat_surgery_intermediateTime = 8;
force force kat_surgery_npwt_MedLevel = 2;
force force kat_surgery_npwtLocation = 3;
force force kat_surgery_npwtTime = 5;
force force kat_surgery_openTime = 15;
force force kat_surgery_pericardialtap_MedLevel = 2;
force force kat_surgery_pericardialtapLocation = 3;
force force kat_surgery_pericardialtapTime = 8;
force force kat_surgery_reboa_MedLevel = 2;
force force kat_surgery_reboaLocation = 3;
force force kat_surgery_reboaTime = 8;
force force kat_surgery_simpleChance = 60;
force force kat_surgery_Surgery_ConsciousnessRequirement = 0;
force force kat_surgery_surgicalAction_MedLevel = 2;
force force kat_surgery_surgicalLocation = 3;
force force kat_surgery_ultrasound_MedLevel = 2;
force force kat_surgery_ultrasoundLocation = 3;
force force kat_surgery_ultrasoundTime = 8;

//KAM Pharmacy
force force kat_pharma_allowStackScript_EACA = true; //ToDo
force force kat_pharma_allowStackScript_TXA = true; //ToDo
force force kat_pharma_bandageCycleTime_EACA = 8;
force force kat_pharma_bandageCycleTime_TXA = 5;
force force kat_pharma_blockChance = 20;
force force kat_pharma_carbonateChance = 100;
force force kat_pharma_CheckCoag_Location = 0; //everywhere
force force kat_pharma_CheckCoag_MedLevel = 1; // Medic
force force kat_pharma_CheckCoag_TreatmentTime = 10;
force force kat_pharma_coagulation = true;
force force kat_pharma_coagulation_allow_clot_text = true;
force force kat_pharma_coagulation_allow_EACA_script = true;
force force kat_pharma_coagulation_allow_LargeWounds = false;
force force kat_pharma_coagulation_allow_MediumWounds = true;
force force kat_pharma_coagulation_allow_MinorWounds = true;
force force kat_pharma_coagulation_allow_TXA_script = true;
force force kat_pharma_coagulation_allowOnAI = false;
force force kat_pharma_coagulation_factor_count = 30;
force force kat_pharma_coagulation_factor_limit = 60;
force force kat_pharma_coagulation_factor_regenerate_time = 150;
force force kat_pharma_coagulation_on_all_Bodyparts = true;
force force kat_pharma_coagulation_requireBV = 3.6;
force force kat_pharma_coagulation_requireHR = true;
force force kat_pharma_coagulation_time = 10;
force force kat_pharma_coagulation_time_large = 45;
force force kat_pharma_coagulation_time_medium = 30;
force force kat_pharma_coagulation_time_minor = 15;
force force kat_pharma_coagulation_tourniquetBlock = true;
force force kat_pharma_eacaClearTrauma = true; //match ACE Stitch
force force kat_pharma_ivCheckLimbDamage = false;
force force kat_pharma_IVdrop = 600;
force force kat_pharma_IVdropEnable = false;
force force kat_pharma_IVflowControl = false;
force force kat_pharma_IVreuse = false;
force force kat_pharma_keepScriptRunning_EACA = true;
force force kat_pharma_keepScriptRunning_TXA = true;
force force kat_pharma_kidneyAction = false;
force force kat_pharma_MedicationsRequireInsIV = true;
force force kat_pharma_medLvl_Amiodarone = 2; //Doctor
force force kat_pharma_medLvl_ApplyIO = 1; //Medic
force force kat_pharma_medLvl_ApplyIV = 1; //Medic
force force kat_pharma_medLvl_Atropine = 2; //Doctor
force force kat_pharma_medLvl_Caffeine = 0;
force force kat_pharma_medLvl_Carbonate = 2; //Doctor
force force kat_pharma_medLvl_CWMP = 0;
force force kat_pharma_medLvl_EACA = 1; //
force force kat_pharma_medLvl_EpinephrineIV = 1;
force force kat_pharma_medLvl_Etomidate = 2;
force force kat_pharma_medLvl_Fentanyl = 1;
force force kat_pharma_medLvl_Flumezenil = 2;
force force kat_pharma_medLvl_Ketamine = 1;
force force kat_pharma_medLvl_Lidocaine = 1;  //Medic
force force kat_pharma_medLvl_Lorazepam = 2;
force force kat_pharma_medLvl_Nalbuphine = 1;  //Medic
force force kat_pharma_medLvl_Naloxone = 1;  //Medic
force force kat_pharma_medLvl_Nitroglycerin = 2;
force force kat_pharma_medLvl_Norepinephrine = 2;
force force kat_pharma_medLvl_Penthrox = 1;  //Medic
force force kat_pharma_medLvl_Pervitin = 0;
force force kat_pharma_medLvl_Phenylephrine = 2;
force force kat_pharma_medLvl_Reorientation = 0;  //anyone
force force kat_pharma_medLvl_TXA = 1;
force force kat_pharma_pervitinSpeed = 1.15;
force force kat_pharma_Reorientation_Enable = true;
force force kat_pharma_Reorientation_Slap = true;
force force kat_pharma_reorientationChance = 50;
force force kat_pharma_RequireInsIV = true;
force force kat_pharma_RequireInsIVBloodDraw = true;
force kat_pharma_staminaMedication = false;
force force kat_pharma_treatmentTime_Amiodarone = 7;
force force kat_pharma_treatmentTime_ApplyIO = 7;
force force kat_pharma_treatmentTime_ApplyIV = 7;
force force kat_pharma_treatmentTime_Atropine = 7;
force force kat_pharma_treatmentTime_Caffeine = 7;
force force kat_pharma_treatmentTime_Carbonate = 7;
force force kat_pharma_treatmentTime_CWMP = 7;
force force kat_pharma_treatmentTime_EACA = 7;
force force kat_pharma_treatmentTime_EpinephrineIV = 7;
force force kat_pharma_treatmentTime_Etomidate = 2;
force force kat_pharma_treatmentTime_Fentanyl = 7;
force force kat_pharma_treatmentTime_Flumazenil = 2;
force force kat_pharma_treatmentTime_Ketamine = 7;
force force kat_pharma_treatmentTime_Lidocaine = 7;
force force kat_pharma_treatmentTime_Lorazepam = 2;
force force kat_pharma_treatmentTime_Nalbuphine = 7;
force force kat_pharma_treatmentTime_Naloxone = 7;
force force kat_pharma_treatmentTime_Nitroglycerin = 7;
force force kat_pharma_treatmentTime_Norepinephrine = 7;
force force kat_pharma_treatmentTime_Penthrox = 8;
force force kat_pharma_treatmentTime_Pervitin = 5;
force force kat_pharma_treatmentTime_Phenylephrine = 7;
force force kat_pharma_treatmentTime_Reorientation = 2;
force force kat_pharma_treatmentTime_TXA = 7;
force force kat_pharma_weapon_sway_pervitin = true;

//KAM Opthalmology
force force kat_ophthalmology_enable = false;
force force kat_ophthalmology_eyeshield_medic_required = 0;
force force kat_ophthalmology_eyeshield_treatment_time = 2;
force force kat_ophthalmology_eyewash_medic_required = 0;
force force kat_ophthalmology_eyewash_treatment_time = 2;
force force kat_ophthalmology_probability_dust = 5;
force force kat_ophthalmology_probability_dust_heavy = 1;
force force kat_ophthalmology_probability_treatment_dust = 20;

//KAM Misc
kat_misc_AFAK_Container = 0;
kat_misc_AFAK_Item_Color = [0.67,0.84,0.9];
kat_misc_AFAK_RemoveWhenEmpty = true;
kat_misc_AFAK_Slot_Color = [1,0.96,0.32];
kat_misc_AFAKFifthSlotItem = "[['kat_guedel', 4]]";
kat_misc_AFAKFirstSlotItem = "[['ACE_tourniquet', 4], ['ACE_splint', 2]]";
kat_misc_AFAKFourthSlotItem = "[['kat_chestSeal', 3], ['kat_ncdKit', 3]]";
kat_misc_AFAKSecondSlotItem = "[['ACE_packingBandage', 10], ['ACE_quikclot', 10]]";
kat_misc_AFAKSixthSlotItem = "[['ACE_epinephrine', 3], ['kat_Carbonate', 1]]";
kat_misc_AFAKThirdSlotItem = "[['ACE_morphine', 3], ['kat_Penthrox', 1], ['kat_Painkiller', 1]]";
force force kat_misc_allowSharedVehicleEquipment = 4;
force force kat_misc_armbandSlingLeftArm = "[0.2, -0.39, -0.2]";
force force kat_misc_armbandSlingLeftArmRotation = "[240, 33, 26]";
force force kat_misc_armbandSlingLeftLeg = "[0.435, -0.075, -0.38]";
force force kat_misc_armbandSlingLeftLegRotation = "[-160, -5, 45]";
force force kat_misc_armbandSlingRightArm = "[-0.228, -0.1, -0.43]";
force force kat_misc_armbandSlingRightArmRotation = "[5, -5, -5]";
force force kat_misc_armbandSlingRightLeg = "[-0.32, -0.29, -0.42]";
force force kat_misc_armbandSlingRightLegRotation = "[-30, -5, 38]";
force force kat_misc_enable = true;
force force kat_misc_enableStitchFullBody = false;
kat_misc_IFAK_Container = 0;
kat_misc_IFAK_Item_Color = [0.67,0.84,0.9];
kat_misc_IFAK_RemoveWhenEmpty = true;
kat_misc_IFAK_Slot_Color = [1,0.3,0.3];
kat_misc_IFAKFirstSlotItem = "[['ACE_tourniquet', 2]]";
kat_misc_IFAKFourthSlotItem = "[['kat_chestSeal', 1]]";
kat_misc_IFAKSecondSlotItem = "[['ACE_packingBandage', 5], ['ACE_quikclot', 5]]";
kat_misc_IFAKThirdSlotItem = "[['kat_Painkiller', 1]]";
force force kat_misc_incompatibilityWarning = true;
kat_misc_MFAK_Container = 0;
kat_misc_MFAK_Item_Color = [0.67,0.84,0.9];
kat_misc_MFAK_RemoveWhenEmpty = true;
kat_misc_MFAK_Slot_Color = [0.56,0.93,0.56];
kat_misc_MFAKEighthSlotItem = "[['kat_Pulseoximeter', 1], ['kat_pocketBVM', 1], ['kat_AED', 1]]";
kat_misc_MFAKFifthSlotItem = "[['kat_larynx', 6]]";
kat_misc_MFAKFirstSlotItem = "[['ACE_tourniquet', 6], ['ACE_splint', 4]]";
kat_misc_MFAKFourthSlotItem = "[['kat_chestSeal', 6], ['kat_aatKit', 3], ['kat_ncdKit', 3], ['kat_stethoscope', 1]]";
kat_misc_MFAKSecondSlotItem = "[['ACE_packingBandage', 15], ['ACE_quikclot', 15], ['ACE_fieldDressing', 15]]";
kat_misc_MFAKSeventhSlotItem = "[['ACE_salineIV_250', 4], ['kat_IV_16', 4]]";
kat_misc_MFAKSixthSlotItem = "[['ACE_epinephrine', 6], ['kat_IV_16', 4], ['kat_nitroglycerin', 2], ['kat_phenylephrine', 2], ['kat_atropine', 2], ['kat_naloxone', 2], ['kat_Carbonate', 1]]";
kat_misc_MFAKThirdSlotItem = "[['ACE_morphine', 6], ['kat_Painkiller', 2], ['kat_Penthrox', 2]]";
force force kat_misc_tourniquetEffects_Enable = true;
force force kat_misc_tourniquetEffects_NegativeMultiplier = 1;
force force kat_misc_tourniquetEffects_PositiveMultiplier = 1;
force force kat_misc_treatmentTimeDetachTourniquet = 7;

//KAM Hypothermia
force force kat_hypothermia_hypothermiaActive = false;

//KAM GUI
kat_gui_ColoredLogs = true;
kat_gui_showPatientSideLabels = true;

//KAM Feedback
force force kat_feedback_effectLowSpO2 = 90;
kat_feedback_enableOpioidEffect = true;

//KAM Circulation
// KAT - ADV Medical: Circulation
force force kat_circulation_abgEnable = false;
force force kat_circulation_AdvRhythm = true;
force force kat_circulation_AdvRhythm_AED_ROSC_Chance = 50;
force force kat_circulation_AdvRhythm_asystoleBloodlossThreshold = 3.6;
force force kat_circulation_AdvRhythm_canDeteriorate = true;
force force kat_circulation_AdvRhythm_CPR_ROSC_Chance = 5;
force force kat_circulation_AdvRhythm_deteriorateAfterTreatment = true;
force force kat_circulation_AdvRhythm_deteriorateTimeMax = 900;
force force kat_circulation_AdvRhythm_deteriorateTimeWeight = 180;
force force kat_circulation_AdvRhythm_Hardcore_Enable = false;
force force kat_circulation_AdvRhythm_hardcoreDeteriorationChance = 10;
force force kat_circulation_AdvRhythm_HTHold = true;
force force kat_circulation_AdvRhythm_PEAChance = 50;
force force kat_circulation_AdvRhythm_PEAEnabled = false;
force force kat_circulation_AdvRhythm_VTChance = 50;
force force kat_circulation_AED_duringCpr = false;
force force kat_circulation_AED_MaxChance = 80;
force force kat_circulation_AED_MinChance = 45;
force force kat_circulation_AED_X_MaxChance = 90;
force force kat_circulation_AED_X_MinChance = 50;
force force kat_circulation_AED_X_Monitor_SpO2Warning = 85;
force force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval = 0;
force force kat_circulation_AED_X_VitalsMonitor_BloodPressureInterval_Time = 30;
force force kat_circulation_AED_X_VitalsMonitor_SoundsSelect = 1;
force force kat_circulation_AEDX_VitalsMonitor_AttachTime = 6;
force force kat_circulation_AEDX_VitalsMonitor_DetachTime = 3;
force force kat_circulation_blood_draw_limit = 3.6;
force force kat_circulation_blood_drawTime_250ml = 25;
force force kat_circulation_blood_drawTime_500ml = 50;
force force kat_circulation_bloodGroups = false;
force force kat_circulation_bloodTypeCustomList = "O,O,A,A,O_N,B,A_N,AB,B_N,AB_N";
force force kat_circulation_bloodTypeRandomWeighted = true;
force force kat_circulation_bloodTypeSetting = 4;
kat_circulation_bloodTypeSettingPlayer = "O_N";
force force kat_circulation_cardiacArrestBleedRate = 0.05;
force force kat_circulation_CPR_ChanceInterval = 15;
force force kat_circulation_CPR_MaxChance_Default = 20;
force force kat_circulation_CPR_MaxChance_Doctor = 40;
force force kat_circulation_CPR_MaxChance_RegularMedic = 30;
force force kat_circulation_CPR_MinChance_Default = 10;
force force kat_circulation_CPR_MinChance_Doctor = 20;
force force kat_circulation_CPR_MinChance_RegularMedic = 15;
force force kat_circulation_CPR_OxygenationPeriod = 15;
force force kat_circulation_Defibrillator_DistanceLimit = 6;
force force kat_circulation_DefibrillatorPads_AttachTime = 6;
force force kat_circulation_DefibrillatorPads_DetachTime = 3;
force force kat_circulation_deterioratingTamponade_chance = 0;
force force kat_circulation_deterioratingTamponade_interval = 60;
force force kat_circulation_enable = true;
force force kat_circulation_enable_CPR_Chances = true;
force force kat_circulation_enable_selfBloodDraw = 1;
force force kat_circulation_hardcoreDiagnose = false;
force force kat_circulation_medLvl_AED = 0;
force force kat_circulation_medLvl_AED_Station_Interact = 0;
force force kat_circulation_medLvl_AED_X = 0;
force force kat_circulation_medLvl_BPCuff = 0;
force force kat_circulation_medLvl_StethHR = 1;
force force kat_circulation_tamponadeChance = 0;
force force kat_circulation_treatmentTime_BPCuff = 12;
force force kat_circulation_treatmentTime_StethHR = 8;
force kat_circulation_useLocation_AED = 0; //everywhere

//KAM Chemical
// KAT - ADV Medical: Chemical
// not used!
force force kat_chemical_availGasmask = "'G_AirPurifyingRespirator_01_F', 'kat_mask_M50', 'kat_mask_M04'";
force force kat_chemical_gasmask_durability = 900;
force force kat_chemical_gasMaskSoundVolume = 1;
force force kat_chemical_infectionTime = 60;
force force kat_chemical_maskStaminaLoss = false;
force force kat_chemical_showPoisoning = true;
force force kat_chemical_tearGasDropChance = 0;


//KAM Breathing
force force kat_breathing_advPtxChance = 5;
force force kat_breathing_advPtxEnable = false;
force force kat_breathing_arrestPneumothorax_interval = 30;
force kat_breathing_availOxyHelmet = "'H_PilotHelmetFighter_B', 'H_PilotHelmetFighter_O', 'H_PilotHelmetFighter_I', 'H_PilotHelmetFighter_I_E'";
force kat_breathing_availOxyMask = "'kat_mask_solr'";
force force kat_breathing_BVMOxygen_Multiplier = 1;
force force kat_breathing_clearChestSealAfterTreatment = true;
force force kat_breathing_deepPenetratingInjuryChance = 30;
force force kat_breathing_deterioratingPneumothorax_chance = 50;
force force kat_breathing_deterioratingPneumothorax_interval = 60;
force force kat_breathing_enable = true;
force force kat_breathing_enable_selfChestseal = 1;
force force kat_breathing_enableCheckBreathing = true;
force force kat_breathing_Etco2_Enabled = true;
force force kat_breathing_Etco2_Units = 0;
force force kat_breathing_HPTXBleedAmount = 0.06;
force force kat_breathing_hptxChance = 5;
force force kat_breathing_inspectChest_enable = 2;
force force kat_breathing_inspectChest_medLvl = 1;
force force kat_breathing_inspectChest_time = 6;
force force kat_breathing_locationProvideOxygen = 3; //facilities and vehicles
force force kat_breathing_medLvl_BVM = 1; //medics
force force kat_breathing_medLvl_BVM_Oxygen = 1; //medics
force force kat_breathing_medLvl_Chestseal = 0; //anyone
force force kat_breathing_medLvl_hemopneumothoraxTreatment = 1; //Doctor
force force kat_breathing_medLvl_NasalCannula = 1; //Medics
force force kat_breathing_medLvl_PocketBVM = 1; //Medics
force force kat_breathing_medLvl_Pulseoximeter = 0; //anyone
force force kat_breathing_mildValue = 75;
force force kat_breathing_NasalCannula_time = 3;
force force kat_breathing_paco2Active = false;
force force kat_breathing_PneumothoraxAlwaysVisible = false;
force force kat_breathing_PneumothoraxArrest = true;
force force kat_breathing_pneumothoraxChance = 5;
force force kat_breathing_pneumothoraxDamageThreshold = 0.4;
force force kat_breathing_pneumothoraxDamageThreshold_TakenDamage = true;
force force kat_breathing_PortableOxygenTank_RefillTime = 5;
force force kat_breathing_PulseOximeter_SpO2Warning = 85;
force force kat_breathing_severeValue = 66; //kurz vor Tod
force force kat_breathing_showCyanosis = true;
force force kat_breathing_showPneumothorax_dupe = false;
force force kat_breathing_slightValue = 90;
force force kat_breathing_SpO2_cardiacActive = true;
force force kat_breathing_SpO2_cardiacValue = 75;
force force kat_breathing_SpO2_dieActive = true;
force force kat_breathing_SpO2_dieValue = 65;
force force kat_breathing_SpO2_MultiplyNegative = 1;
force force kat_breathing_SpO2_MultiplyPositive = 1;
force force kat_breathing_SpO2_perfusion = true;
force force kat_breathing_SpO2_PerfusionMultiplier = 1;
force force kat_breathing_SpO2_unconscious = 75;
force force kat_breathing_Stable_spo2 = 85;
force force kat_breathing_staminaLossAtLowSPO2 = true;
force force kat_breathing_stethoscopeListeningTime = 15;
force force kat_breathing_stethoscopeSoundVolume = 2;
force force kat_breathing_TensionHemothoraxAlwaysVisible = false;

//KAM Airway
// KAT - ADV Medical: Airway
force force kat_airway_Accuvac_time = 8;
force force kat_airway_autoTriage = false;
force force kat_airway_block_headTurning_ifAirwayItem = true;
force force kat_airway_CancelRecoveryPosition_Time = 3;
force force kat_airway_CheckAirway_time = 2;
kat_airway_checkbox_puking_sound = true;
force force kat_airway_enable = true;
force force kat_airway_Guedeltubus_time = 6;
force force kat_airway_HeadTurn_Interval = 3;
force force kat_airway_Hyperextend_Time = 3;
force force kat_airway_Larynxtubus_time = 3;
force force kat_airway_medLvl_Accuvac = 1; //Medic
force force kat_airway_medLvl_Guedeltubus = 1; //Medic
force force kat_airway_medLvl_Larynxtubus = 1; //Medic
force force kat_airway_medLvl_Suction = 1; //Medic
force force kat_airway_occlusion_cooldownPeriod = 6;
force force kat_airway_occlusion_repeatTimer = 60;
force force kat_airway_probability_headturning = 50;
force force kat_airway_probability_obstruction = 15;
force force kat_airway_probability_occluded = 10;
force force kat_airway_RecoveryPosition_Time = 6;
force force kat_airway_RecoveryPosition_TimeToDrain = 10;
force force kat_airway_ReusableAirwayItems = false;
force force kat_airway_string_exit = "";
force force kat_airway_Suction_reuse = true;
force force kat_airway_Suction_time = 12;
