if (!local player) exitWith {};

comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add weapons";
player addWeapon "BWA3_G38C";
player addPrimaryWeaponItem "ACE_muzzle_mzls_L";
player addPrimaryWeaponItem "ACE_DBAL_A3_Green";
player addPrimaryWeaponItem "BWA3_optic_ZO4x30i_MicroT2_pip";
player addPrimaryWeaponItem "BWA3_30Rnd_556x45_G36_AP";
player addWeapon "CUP_hgun_M17_Black";
player addHandgunItem "CUP_acc_MLPLS_Laser";
player addHandgunItem "optic_MRD_black";
player addHandgunItem "CUP_21Rnd_9x19_M17_Black";

comment "Add containers";
player forceAddUniform "BWA3_Uniform_Crye_G3_Fleck";
player addVest "CUP_V_B_GER_PVest_Fleck_Med_LT";
player addBackpack "ttt_backpack_medic_rgr_01";

comment "Add binoculars";
player addWeapon "Binocular";

comment "Add items to containers";
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 20 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToUniform "kat_chestSeal";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 20 do {player addItemToUniform "ACE_suture";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_Flashlight_MX991";
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 5 do {player addItemToUniform "kat_IV_16";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACRE_PRC152";
player addItemToUniform "acex_intelitems_notepad";
player addItemToUniform "ACE_Chemlight_IR";
player addItemToVest "kat_stethoscope";
player addItemToVest "kat_Pulseoximeter";
player addItemToVest "ACRE_PRC152";
player addItemToVest "ItemAndroidMisc";
player addItemToVest "ACE_surgicalKit";
for "_i" from 1 to 2 do {player addItemToVest "BWA3_DM25";};
player addItemToVest "BWA3_DM32_Green";
for "_i" from 1 to 6 do {player addItemToVest "BWA3_30Rnd_556x45_G36_AP";};
for "_i" from 1 to 6 do {player addItemToVest "kat_Painkiller";};
for "_i" from 1 to 2 do {player addItemToVest "CUP_21Rnd_9x19_M17_Black";};
player addItemToVest "BWA3_DM32_Blue";
player addItemToBackpack "kat_basicDiagnostic";
for "_i" from 1 to 30 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 50 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_aatKit";};
for "_i" from 1 to 10 do {player addItemToBackpack "kat_IV_16";};
for "_i" from 1 to 3 do {player addItemToBackpack "kat_BVM";};
for "_i" from 1 to 5 do {player addItemToBackpack "kat_suction";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_chestSeal";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_EACA";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_fentanyl";};
for "_i" from 1 to 12 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 12 do {player addItemToBackpack "kat_epinephrineIV";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_ketamine";};
for "_i" from 1 to 5 do {player addItemToBackpack "kat_larynx";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_naloxone";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_nitroglycerin";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_norepinephrine";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_phenylephrine";};
for "_i" from 1 to 50 do {player addItemToBackpack "ACE_suture";};
for "_i" from 1 to 12 do {player addItemToBackpack "kat_TXA";};
player addItemToBackpack "kat_Pulseoximeter";
player addItemToBackpack "kat_accuvac";
for "_i" from 1 to 10 do {player addItemToBackpack "kat_lidocaine";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_amiodarone";};
for "_i" from 1 to 6 do {player addItemToBackpack "kat_atropine";};
player addItemToBackpack "kat_X_AED";
for "_i" from 1 to 2 do {player addItemToBackpack "kat_IO_FAST";};
player addItemToBackpack "ACE_SpraypaintBlue";
player addItemToBackpack "ace_flags_blue";
for "_i" from 1 to 5 do {player addItemToBackpack "BWA3_DM32_Blue";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_Chemlight_HiBlue";};
player addItemToBackpack "B_IR_Grenade";
player addItemToBackpack "kat_oxygenTank_150";
player addHeadgear "BWA3_OpsCore_FastMT_Peltor";
player addGoggles "kat_Armband_Doctor_Goggles";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ACE_Altimeter";
player linkItem "BWA3_ItemNaviPad";

